spring:
  application:
    name: smartHire.api

  datasource:
    url: jdbc:postgresql://localhost:5433/smarthire
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret: "dev-secret-key-dev-secret-key-dev-secret-key-dev-secret-key-123456"
  expiration: 86400000